# Generated by Django 4.2.19 on 2025-05-02 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0002_disease_description_alter_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
