# Generated by Django 5.1.6 on 2025-05-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_disease_description_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='response',
        ),
    ]
