# Generated by Django 4.2.19 on 2025-05-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_chatmessage_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatResponseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='prescriptions.chatmessage')),
            ],
        ),
    ]
