# Generated by Django 4.2.19 on 2025-05-30 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_chatresponsesuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=200)),
                ('medicine_name', models.CharField(max_length=200)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_medicines', to='prescriptions.disease')),
            ],
        ),
    ]
